# Basic Usage

## Importing Numpy

In [2]:
import numpy

In [4]:
numpy.version.version

'2.3.5'

In [6]:
import numpy as np

In [8]:
np.version.version

'2.3.5'

## Creating NumPy Arrays

To create arrays in numpy, we use `numpy.array()`. The syntax is as follows:  

`numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)`

### Creating One Dimensional Arrays

In [11]:
vector_a = np.array([1, 2, 3])
vector_a

array([1, 2, 3])

In [13]:
type(vector_a)

numpy.ndarray

In [20]:
vector_a.dtype

dtype('int64')

In [22]:
vector_b = np.array([1, 2, "c"])
vector_b

array(['1', '2', 'c'], dtype='<U21')

In [24]:
vector_c = np.array([1, 2, 3, 4.5])
vector_c

array([1. , 2. , 3. , 4.5])

In [26]:
vector_c.dtype

dtype('float64')

In [28]:
vector_d = np.array([1, 3, 5, 7], dtype=str)
vector_d

array(['1', '3', '5', '7'], dtype='<U1')

In [30]:
vector_d.dtype

dtype('<U1')

### Check the Shape of Array

In [32]:
vector_d.shape

(4,)

## Creating Multidimensional Array

In [36]:
multi_a = np.array([[1, 2],[3, 4]])
multi_a

array([[1, 2],
       [3, 4]])

In [38]:
multi_a.shape

(2, 2)

In [40]:
multi_b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
multi_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
multi_b.shape

(3, 3)

In [44]:
multi_c = np.array([[1, 2], [3, 4], [4, 5]])
multi_c

array([[1, 2],
       [3, 4],
       [4, 5]])

In [46]:
multi_c.shape

(3, 2)

In [48]:
multi_d = np.array([1, 2, 3], ndmin=5)
multi_d

array([[[[[1, 2, 3]]]]])

In [51]:
multi_d.shape

(1, 1, 1, 1, 3)