# Basic Usage

## Importing Numpy

In [2]:
import numpy

In [4]:
numpy.version.version

'2.3.5'

In [4]:
import numpy as np

In [8]:
np.version.version

'2.3.5'

## Creating NumPy Arrays

To create arrays in numpy, we use `numpy.array()`. The syntax is as follows:  

`numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)`

### Creating One Dimensional Arrays

In [11]:
vector_a = np.array([1, 2, 3])
vector_a

array([1, 2, 3])

In [13]:
type(vector_a)

numpy.ndarray

In [20]:
vector_a.dtype

dtype('int64')

In [22]:
vector_b = np.array([1, 2, "c"])
vector_b

array(['1', '2', 'c'], dtype='<U21')

In [24]:
vector_c = np.array([1, 2, 3, 4.5])
vector_c

array([1. , 2. , 3. , 4.5])

In [26]:
vector_c.dtype

dtype('float64')

In [28]:
vector_d = np.array([1, 3, 5, 7], dtype=str)
vector_d

array(['1', '3', '5', '7'], dtype='<U1')

In [30]:
vector_d.dtype

dtype('<U1')

### Check the Shape of Array

In [32]:
vector_d.shape

(4,)

## Creating Multidimensional Array

In [36]:
multi_a = np.array([[1, 2],[3, 4]])
multi_a

array([[1, 2],
       [3, 4]])

In [38]:
multi_a.shape

(2, 2)

In [40]:
multi_b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
multi_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
multi_b.shape

(3, 3)

In [44]:
multi_c = np.array([[1, 2], [3, 4], [4, 5]])
multi_c

array([[1, 2],
       [3, 4],
       [4, 5]])

In [46]:
multi_c.shape

(3, 2)

In [5]:
multi_d = np.array([1, 2, 3], ndmin=5)
multi_d

array([[[[[1, 2, 3]]]]])

In [6]:
multi_d.shape

(1, 1, 1, 1, 3)

### Creating Arrays with Arange

#### The `arange` function is similar to Python's `range` function. This can be used to create numpy arrays.

In [8]:
arange_a = np.arange(20)
arange_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [9]:
arange_b = np.arange(2, 10)
arange_b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arange_c = np.arange(2, 10, 3)
arange_c

array([2, 5, 8])

### Creating arrays of ones, zeros and empty
Array of ones and zeros of any dimension can be created from numpy.  
`zeros(dim)` will return a np.array of `dim` dimensions initialised with 0. Note that `dim` should be a `tuple`. 

`zeros_like(array)` will return a np.array of same dimensions as of `array` initialised with zeros. 

The functionality is same with `ones` , and `ones_like` except of course the initialization is done with ones. 

The functionality is same with `empty`, and `empty_like` which will create numpy arrays but won't initialise it with anything (hence, faster) By default, all the values in the array will have garbage values. 

In [13]:
zeros_a = np.zeros((3))
zeros_a

array([0., 0., 0.])

zeros_b = np.zeros((3, 4))
zeros_b

In [15]:
zeros_c = np.zeros((3, 3), dtype=int)
zeros_c

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
zeros_like_a = np.zeros_like(zeros_c)
zeros_like_a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
ones_a = np.ones((2, 2))
ones_a

array([[1., 1.],
       [1., 1.]])

In [19]:
task = 7*np.ones((5, 2), dtype=int)
task

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [25]:
empty_a = np.empty((4,5))
empty_a

array([[6.23042070e-307, 3.56043053e-307, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.42419530e-306,
        8.45592576e-307, 6.23054972e-307],
       [2.22522597e-306, 1.06810268e-306, 6.23052935e-307,
        1.78020576e-306, 1.60220800e-306],
       [8.45559303e-307, 1.06811422e-306, 1.05694828e-307,
        1.42410974e-306, 1.42404727e-306]])

In [26]:
empty_like_a = np.empty_like(empty_a)
empty_like_a

array([[6.23042070e-307, 3.56043053e-307, 1.11258854e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.42419530e-306,
        8.45592576e-307, 6.23054972e-307],
       [2.22522597e-306, 1.06810268e-306, 6.23052935e-307,
        1.78020576e-306, 1.60220800e-306],
       [8.45559303e-307, 1.06811422e-306, 1.05694828e-307,
        1.42410974e-306, 1.42404727e-306]])

### Accessing and Slicing NumPy Arrays
To access the elements in an array, we simply pass the index of desired element. 

In [27]:
access_a = np.array([1,2,3,5])
access_a

array([1, 2, 3, 5])

In [29]:
access_a[3]

np.int64(5)

In [30]:
access_b = np.array([[1,2], [8, 9]])
access_b

array([[1, 2],
       [8, 9]])

In [31]:
access_b[1]

array([8, 9])

In [33]:
slice_a = np.arange(11)
slice_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
slice_a[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
slice_a[:4]

array([0, 1, 2, 3])

In [37]:
slice_a[3:7]

array([3, 4, 5, 6])

In [38]:
slice_a[2:7:2]

array([2, 4, 6])

In [39]:
slice_a[::2]

array([ 0,  2,  4,  6,  8, 10])

Slicing NumPy arrays is similar to that of Python lists. One main distinction in Python list and NumPy array is that the slice __is not the copy, but the original array. Hence, if any operations on the slice will be reflected in the original array.__

In [40]:
slice_b = np.arange(16)
slice_b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
slice_b[10:15] = 7

In [43]:
slice_b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,  7,  7,  7,  7,  7, 15])

#### To avoid above scenario, we can use `copy()`

In [45]:
slice_c = np.arange(10)
slice_c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
copy = slice_c.copy()
copy[3:7] = 10

In [47]:
copy

array([ 0,  1,  2, 10, 10, 10, 10,  7,  8,  9])

In [48]:
slice_c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [53]:
slice_multi_dim_a = np.array([[1,2,5], [3,4,7]])
slice_multi_dim_a

array([[1, 2, 5],
       [3, 4, 7]])

In [54]:
slice_multi_dim_a[:]

array([[1, 2, 5],
       [3, 4, 7]])

In [57]:
slice_multi_dim_a.shape

(2, 3)

In [58]:
slice_multi_dim_a[:,0]

array([1, 3])

In [59]:
slice_multi_dim_a[:,0:2]

array([[1, 2],
       [3, 4]])

In [61]:
slice_multi_dim_a[0, 0:2]

array([1, 2])

In [62]:
slice_multi_dim_b = np.array([[1, 2, 3], [4, 5, 6]])
slice_multi_dim_b

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
slice_multi_dim_b[0, :]

array([1, 2, 3])

### Boolean indexing
Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [65]:
bool_a = np.array([[1, 2], [3, 4], [5, 6]])
bool_a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
bool_idx = (bool_a>2)
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [67]:
bool_a[bool_idx]

array([3, 4, 5, 6])

In [5]:
bool_b = np.array(['Python', 'Java', 'Ruby', 'Rust'])
bool_b == "Python"

array([ True, False, False, False])

To work with multiple boolean conditions, we use **|**, **&** operators but not the Python operators **or** and **and**.

In [6]:
(bool_b == 'Python') | (bool_b == 'Ruby')

array([ True, False,  True, False])

### Masking and Indexing

In [9]:
mask_array_a = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)
mask_array_a

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [8]:
np.info(np.linspace)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
rets

In [11]:
mask = mask_array_a % 2 == 0

In [12]:
mask

array([[False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [15]:
masked_array = mask_array_a[mask]
masked_array

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38,
       40, 42, 44, 46, 48, 50])

### Array Mathematics

#### Arithmetic Operations

In [23]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])

output_1 = np.add(x, y) #element wise addition of array x and y
output_2 = x + y
assert np.array_equal(output_1, output_2)
print(f"out1: {output_1} and out2: {output_2}")

out1: [0 0 0] and out2: [0 0 0]


In [25]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1])

output_1 = np.add(x, y) #adding y to each element of x
output_2 = x + y 
print(f'out1: {output_1} and out2: {output_2}')

out1: [2 3 4 5 6] and out2: [2 3 4 5 6]


*Note: Subtraction, Multiplication and Division can be cmarried out in the same fashion using `np.subtract`, `np.multiply` and `np.divide`.  
For Floor division `np.floor_division` can be used.*

In [29]:
x = np.array([1, 2, .2])
output_1 = np.reciprocal(x)
output_2 = 1/x
assert np.array_equal(output_1, output_2)
print(f'out1: {output_1} and out2: {output_2}')

out1: [1.  0.5 5. ] and out2: [1.  0.5 5. ]


### Trigonometic Operations

#### Calculation of sine, cosine, tangent, element-wise

In [32]:
x = np.array([0., 1., 30, 90, 120, 150, 180])
print("sine:", np.sin(x))
print("cosine:", np.cos(x))
print("tangent:", np.tan(x))

sine: [ 0.          0.84147098 -0.98803162  0.89399666  0.58061118 -0.71487643
 -0.80115264]
cosine: [ 1.          0.54030231  0.15425145 -0.44807362  0.81418097  0.69925081
 -0.59846007]
tangent: [ 0.          1.55740772 -6.4053312  -1.99520041  0.71312301 -1.02234624
  1.33869021]


#### Calculation of inverse sine, inverse cosine, and inverse tangent, element-wise.

In [34]:
x = np.array([-1, 0, 1])
print("sine:", np.arcsin(x))
print("cosine:", np.arccos(x))
print("tangent:", np.arctan(x))

sine: [-1.57079633  0.          1.57079633]
cosine: [3.14159265 1.57079633 0.        ]
tangent: [-0.78539816  0.          0.78539816]


#### Converts angles from radian to degrees

In [36]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])

output_1 = np.degrees(x)
output_2 = np.rad2deg(x)
assert np.array_equiv(output_1, output_2)
print(f'out1: {output_1} and out2: {output_2}')

out1: [-180.  -90.   90.  180.] and out2: [-180.  -90.   90.  180.]


#### Convert angles from degrees to radian

In [37]:
x = np.array([-180.,  -90.,   90.,  180.])

output_1 = np.radians(x)
output_2 = np.deg2rad(x)
assert np.array_equiv(output_1, output_2)
print(f'out1: {output_1} and out2: {output_2}')

out1: [-3.14159265 -1.57079633  1.57079633  3.14159265] and out2: [-3.14159265 -1.57079633  1.57079633  3.14159265]


### Statistics and Linear Algebra

In [38]:
x = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
x.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [40]:
sum_a = x.sum()
sum_a

np.int64(36)

In [41]:
sum_across_col = x.sum(axis=0)
sum_across_col

array([ 6,  8, 10, 12])

In [44]:
sum_across_row = x.sum(axis=1)
sum_across_row

array([10, 26])

In [45]:
mean = x.mean()
mean

np.float64(4.5)

In [46]:
mean_across_col = x.mean(axis=0)
mean_across_col

array([3., 4., 5., 6.])

In [47]:
mean_across_row = x.mean(axis=1)
mean_across_row

array([2.5, 6.5])

In [48]:
array_a = np.array([[1, 2, 3, 4, 5],[1, 3, 4, 6, 7]])
array_b = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [49]:
array_a

array([[1, 2, 3, 4, 5],
       [1, 3, 4, 6, 7]])

In [52]:
array_a * 3

array([[ 3,  6,  9, 12, 15],
       [ 3,  9, 12, 18, 21]])

In [53]:
array_a.dot(array_b.T)

array([[110,  95],
       [156, 135]])