### Numpy using Matrices

In [2]:
import numpy as np

In [7]:
mat_a = np.asmatrix([[1, 2], [3, 4]])
mat_a

matrix([[1, 2],
        [3, 4]])

In [9]:
mat_a.size

4

In [11]:
mat_b = np.asmatrix('1, 2; 3, 4')
mat_b

matrix([[1, 2],
        [3, 4]])

In [12]:
mat_c = np.matrix('1, 2; 3, 4; 5, 6')
mat_c

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [13]:
mat_c.ndim

2